# Generated by Django 4.2.21 on 2025-05-31 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0021_highlight_link_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('chat', '0008_message_shared_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text="A short description of the action, e.g., 'released', 'followed you'.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional: More details about the notification or a preview.', null=True)),
                ('notification_type', models.CharField(choices=[('NEW_RELEASE', 'New Release'), ('NEW_FOLLOWER', 'New Follower'), ('SALE_MADE_ARTIST', 'Sale Made (Artist)'), ('NEW_CHAT_MESSAGE', 'New Chat Message')], db_index=True, max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_artist_channel', models.BooleanField(db_index=True, default=False, help_text="Is this notification for the artist's activity channel (sales, follows)?")),
                ('actor_artist', models.ForeignKey(blank=True, help_text='The artist profile that performed the action (e.g., released music).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications_as_artist', to='music.artist')),
                ('actor_user', models.ForeignKey(blank=True, help_text='The user who performed the action (e.g., followed, sent message).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications_as_user', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The user who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_artist_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about_artist_profile', to='music.artist')),
                ('target_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about', to='chat.conversation')),
                ('target_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_about', to='shop.order')),
                ('target_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about', to='music.release')),
                ('target_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about_user_profile_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['recipient', 'is_artist_channel', 'is_read', 'created_at'], name='notificatio_recipie_f070dd_idx')],
            },
        ),
    ]
