# Generated by Django 4.2.21 on 2025-05-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_track_audio_file'),
        ('chat', '0002_conversation_initiator_conversation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='related_artist',
            field=models.ForeignKey(blank=True, help_text='If this conversation is directed towards an artist profile, this links to that artist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_context_conversations', to='music.artist'),
        ),
    ]
