# Generated by Django 4.2.21 on 2025-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_related_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_attachment_filename',
            field=models.CharField(blank=True, help_text='The original uploaded filename for the attachment.', max_length=255, null=True),
        ),
    ]
