# Generated by Django 4.2.21 on 2025-05-27 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0011_alter_track_audio_file'),
        ('chat', '0005_rename_sender_to_sender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_identity_type',
            field=models.CharField(choices=[('USER', 'User'), ('ARTIST', 'Artist')], default='USER', help_text='The identity (User or Artist) used by the sender for this message.', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='sending_artist',
            field=models.ForeignKey(blank=True, help_text='The artist profile used for sending, if sender_identity_type is ARTIST.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages_as_artist', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_identity_type', 'sending_artist'], name='chat_messag_sender__c3d005_idx'),
        ),
    ]
