# Generated by Django 4.2.21 on 2025-05-27 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0011_alter_track_audio_file'),
        ('chat', '0006_message_sender_identity_type_message_sending_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='related_artist',
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator_artist_profile',
            field=models.ForeignKey(blank=True, help_text='If initiator_identity_type is ARTIST, this links to their artist profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_artist_conversations', to='music.artist'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator_identity_type',
            field=models.CharField(choices=[('USER', 'User'), ('ARTIST', 'Artist')], default='USER', help_text='The identity (User or Artist) the initiator used for this conversation.', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator_user',
            field=models.ForeignKey(blank=True, help_text='The actual user who created this conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_user_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_artist_recipient',
            field=models.ForeignKey(blank=True, help_text='If this conversation is directed towards an artist profile, this links to that target artist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_artist_conversations', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='message',
            name='original_attachment_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_identity_type',
            field=models.CharField(choices=[('USER', 'User'), ('ARTIST', 'Artist')], help_text='The identity (User or Artist) used by the sender for this message.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['initiator_identity_type', 'initiator_artist_profile'], name='chat_conver_initiat_edcd8a_idx'),
        ),
    ]
