# Generated by Django 4.2.21 on 2025-05-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_highlight_link_url'),
        ('chat', '0007_remove_conversation_initiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_track',
            field=models.ForeignKey(blank=True, help_text='The track shared in this message, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_shares', to='music.track'),
        ),
    ]
