# Generated by Django 4.2.21 on 2025-05-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price set by user for NYP items at the time of adding to cart (in product's original currency).", max_digits=10, null=True),
        ),
    ]
