# Generated by Django 4.2.21 on 2025-05-26 00:58

from django.db import migrations, models
import users.models
import vaultwave.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_path, validators=[vaultwave.utils.validate_image_not_gif_utility]),
        ),
    ]
