# Generated by Django 4.2.21 on 2025-05-31 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0021_highlight_link_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(help_text='The artist being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='music.artist')),
                ('user', models.ForeignKey(help_text='The user who is following.', on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'artist'], name='interaction_user_id_268610_idx')],
                'unique_together': {('user', 'artist')},
            },
        ),
    ]
