# Generated by Django 4.2.20 on 2025-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_location_artist_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='track',
            name='duration_in_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds (auto-populated)', null=True),
        ),
    ]
