# Generated by Django 4.2.21 on 2025-05-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_duration_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='releases', to='music.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.genre'),
        ),
    ]
