# Generated by Django 4.2.21 on 2025-05-25 12:32

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_seed_initial_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_picture',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.artist_pic_path, validators=[music.models.validate_image_not_gif]),
        ),
        migrations.AlterField(
            model_name='release',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.cover_art_path, validators=[music.models.validate_image_not_gif]),
        ),
    ]
