# Generated by Django 4.2.21 on 2025-05-26 00:58

from decimal import Decimal
from django.db import migrations, models
# import music.models # Keep commented or remove if not used for anything else in THIS file

# Define a dummy function placeholder.
# This function will not actually be called by the new migration we are creating.
# It's here so that makemigrations can load this historical migration file.
def old_release_download_path_placeholder_0007(instance, filename):
    return f'historical_release_downloads_0007/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_artist_artist_picture_alter_release_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', help_text="Currency for 'Paid' model.", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='download_file',
            # Use the placeholder for the historical reference
            field=models.FileField(blank=True, help_text='The downloadable file for the release (e.g., ZIP archive).', null=True, upload_to=old_release_download_path_placeholder_0007),
        ),
        migrations.AddField(
            model_name='release',
            name='minimum_price_nyp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Minimum price for 'Name Your Price' model. Can be 0.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price for 'Paid' model. Leave blank if not 'Paid'.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='pricing_model',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('NYP', 'Name Your Price')], default='PAID', help_text='Choose the pricing model for downloads.', max_length=10),
        ),
    ]