# Generated by Django 4.2.21 on 2025-05-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_release_currency_release_download_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='download_file',
            field=models.FileField(blank=True, help_text='The downloadable file for the release (e.g., ZIP archive) uploaded by the musician.', null=True, upload_to=music.models.release_download_path),
        ),
        migrations.CreateModel(
            name='GeneratedDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_format', models.CharField(choices=[('MP3_320', 'MP3 (320kbps)'), ('MP3_192', 'MP3 (192kbps)'), ('FLAC', 'FLAC'), ('WAV', 'WAV (Original Quality)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('download_file', models.FileField(blank=True, help_text='The generated ZIP file for download.', null=True, upload_to=music.models.generated_release_download_path)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for download URL', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this download link/file expires.', null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_downloads', to='music.release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='music_gener_status_6f3c16_idx')],
            },
        ),
    ]
