# Generated by Django 4.2.21 on 2025-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_release_download_file_generateddownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bit_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Bit rate in kbit/s (e.g., 320, 1411)', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='channels',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of audio channels (e.g., 1 for mono, 2 for stereo)', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='codec_name',
            field=models.CharField(blank=True, help_text='Audio codec (e.g., mp3, flac, pcm_s16le)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_lossless',
            field=models.BooleanField(blank=True, help_text='True if the original uploaded format is lossless', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='sample_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Sample rate in Hz (e.g., 44100, 48000)', null=True),
        ),
        migrations.AlterField(
            model_name='generateddownload',
            name='requested_format',
            field=models.CharField(choices=[('MP3_320', 'MP3 (320kbps)'), ('MP3_192', 'MP3 (192kbps)'), ('FLAC', 'FLAC (Lossless)'), ('WAV', 'WAV (Uncompressed Lossless)'), ('ORIGINAL_ZIP', 'Original Files (Zipped)')], max_length=20),
        ),
    ]
