# Generated by Django 4.2.21 on 2025-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_track_bit_rate_track_channels_track_codec_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddownload',
            name='requested_format',
            field=models.CharField(choices=[('MP3_320', 'MP3 (320kbps)'), ('MP3_192', 'MP3 (192kbps)'), ('FLAC', 'FLAC (Lossless)'), ('WAV', 'WAV (Uncompressed Lossless)'), ('ORIGINAL_ZIP', 'Original Files')], max_length=20),
        ),
    ]
