# Generated by Django 4.2.21 on 2025-05-27 10:00

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_generateddownload_requested_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(max_length=255, upload_to=music.models.track_audio_path),
        ),
    ]
