# Generated by Django 4.2.21 on 2025-05-30 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0011_alter_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='listen_count',
            field=models.PositiveIntegerField(default=0, help_text='Aggregated significant listens for this release.'),
        ),
        migrations.AddField(
            model_name='track',
            name='listen_count',
            field=models.PositiveIntegerField(default=0, help_text='Aggregated significant listens for this track.'),
        ),
        migrations.CreateModel(
            name='ListenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_start_timestamp_utc', models.DateTimeField(help_text='UTC timestamp when this unmuted listening segment started.')),
                ('reported_listen_duration_ms', models.PositiveIntegerField(help_text='Duration of this unmuted listening segment in milliseconds, reported by client.')),
                ('listened_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this event was logged by the backend.')),
                ('is_significant', models.BooleanField(db_index=True, default=False, help_text='True if this listen event meets the criteria for a significant listen.')),
                ('is_processed_for_totals', models.BooleanField(db_index=True, default=False, help_text='Helper flag for batch aggregation tasks, if implemented.')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listen_events', to='music.release')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_events', to='music.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listen_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listened_at'],
                'indexes': [models.Index(fields=['track', 'is_significant', 'listened_at'], name='music_liste_track_i_736251_idx'), models.Index(fields=['release', 'is_significant', 'listened_at'], name='music_liste_release_543979_idx'), models.Index(fields=['user', 'is_significant', 'listened_at'], name='music_liste_user_id_3ad6f3_idx')],
            },
        ),
    ]
