# Generated by Django 4.2.21 on 2025-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_release_listen_count_track_listen_count_listenevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listenevent',
            name='music_liste_track_i_736251_idx',
        ),
        migrations.RemoveIndex(
            model_name='listenevent',
            name='music_liste_release_543979_idx',
        ),
        migrations.RemoveIndex(
            model_name='listenevent',
            name='music_liste_user_id_3ad6f3_idx',
        ),
        migrations.RemoveField(
            model_name='listenevent',
            name='is_processed_for_totals',
        ),
        migrations.RemoveField(
            model_name='listenevent',
            name='is_significant',
        ),
        migrations.AddIndex(
            model_name='listenevent',
            index=models.Index(fields=['track', 'listened_at'], name='music_liste_track_i_d04903_idx'),
        ),
        migrations.AddIndex(
            model_name='listenevent',
            index=models.Index(fields=['release', 'listened_at'], name='music_liste_release_eeb60c_idx'),
        ),
        migrations.AddIndex(
            model_name='listenevent',
            index=models.Index(fields=['user', 'listened_at'], name='music_liste_user_id_2d5054_idx'),
        ),
    ]
