# Generated by Django 4.2.21 on 2025-05-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0013_remove_listenevent_music_liste_track_i_736251_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='download_file',
        ),
        migrations.AlterField(
            model_name='generateddownload',
            name='download_file',
            field=models.FileField(blank=True, help_text='The generated ZIP file for download.', null=True, upload_to=music.models.generated_release_download_path),
        ),
        migrations.AlterField(
            model_name='listenevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
