# Generated by Django 4.2.21 on 2025-05-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import music.models
import vaultwave.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0014_remove_release_download_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', '-display_start_datetime', '-created_at']},
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='highlighted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='highlighted_by',
        ),
        migrations.AddField(
            model_name='highlight',
            name='carousel_description',
            field=models.TextField(blank=True, help_text='Optional: Description for the carousel slide.'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='carousel_subtitle',
            field=models.CharField(blank=True, help_text='Optional: Subtitle for the carousel slide.', max_length=200),
        ),
        migrations.AddField(
            model_name='highlight',
            name='carousel_title',
            field=models.CharField(blank=True, help_text='Optional: Carousel title override. Defaults to release title.', max_length=200),
        ),
        migrations.AddField(
            model_name='highlight',
            name='created_by',
            field=models.ForeignKey(help_text='Admin/Staff user who created this highlight.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_highlights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highlight',
            name='custom_carousel_image',
            field=models.ImageField(blank=True, help_text='Optional: Custom image for carousel. Defaults to release cover art.', null=True, upload_to=music.models.highlight_custom_image_path, validators=[vaultwave.utils.validate_image_not_gif_utility]),
        ),
        migrations.AddField(
            model_name='highlight',
            name='display_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Optional: When this highlight should stop being displayed. Leave blank for indefinite.', null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='display_start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this highlight should start being displayed.'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manually activate or deactivate this highlight.'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display (e.g., 0 is first).'),
        ),
    ]
