# Generated by Django 4.2.21 on 2025-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_highlight_carousel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Description for the highlight (max 255 chars).', max_length=255),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional: Subtitle for the highlight (max 64 chars).', max_length=64),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Highlight title (max 100 chars). Defaults to release title.', max_length=100),
        ),
    ]
