# Generated by Django 4.2.21 on 2025-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_highlight_description_alter_highlight_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Highlight title (max 70 chars). Defaults to release title.', max_length=70),
        ),
    ]
