# Generated by Django 4.2.21 on 2025-05-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_highlight_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display (e.g., 0 is first). Must be unique.', unique=True),
        ),
    ]
