# Generated by Django 4.2.21 on 2025-05-31 00:10

from django.db import migrations, models
import django.db.models.deletion
import music.models
import vaultwave.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_highlight_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='custom_carousel_image',
            field=models.ImageField(blank=True, help_text='Optional: Custom image for carousel. If no release, this might be required.', null=True, upload_to=music.models.highlight_custom_image_path, validators=[vaultwave.utils.validate_image_not_gif_utility]),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='music.release'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Highlight title (max 70 chars). If no release, this is required.', max_length=70),
        ),
    ]
