# Generated by Django 4.2.21 on 2025-05-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_highlight_custom_carousel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional URL for generic highlights or to override release link.', null=True),
        ),
    ]
